music={

 "bairan":"https://www.youtube.com/watch?v=oafxkMv4xnc&list=RDoafxkMv4xnc&start_radio=1&pp=ygULYmFpcmFuIHNvbmegBwE%3D",
 "shky shky":"https://www.youtube.com/watch?v=sUf2PtEZris&list=RDsUf2PtEZris&start_radio=1&pp=ygUQc2hha3kgc2hha3kgc29uZ6AHAQ%3D%3D",
 "dimple":"https://www.youtube.com/watch?v=CNt7V99wsn4&list=RDCNt7V99wsn4&start_radio=1&pp=ygULZGltcGxlIHNvbmegBwE%3D",
 "ranjhan":"https://www.youtube.com/watch?v=lBvbNxiVmZA&list=RDlBvbNxiVmZA&start_radio=1&pp=ygUNcmFuamhhbmEgc29uZ6AHAQ%3D%3D",
 "raanshanaa":"https://www.youtube.com/watch?v=75o1iC1OSrE&list=RD75o1iC1OSrE&start_radio=1&pp=ygUNcmFuamhhbmEgc29uZ6AHAQ%3D%3D",
 "Jugraafiya":"https://www.youtube.com/watch?v=gRRMSF0nB0c&list=RDgRRMSF0nB0c&start_radio=1&pp=ygUKanVncmFhZml5YaAHAQ%3D%3D",
 "Jo tum mere ho":"https://www.youtube.com/watch?v=ilNt2bikxDI&list=RDilNt2bikxDI&start_radio=1&pp=ygUOam8gdHVtIG1lcmUgaG-gBwE%3D",
 "kesariya":"https://www.youtube.com/watch?v=BddP6PYo2gs&list=RDBddP6PYo2gs&start_radio=1&pp=ygUIa2VzYXJpeWGgBwE%3D",
 "mashup":"https://www.youtube.com/watch?v=kjpFX1y_Xlg&list=RDkjpFX1y_Xlg&start_radio=1&pp=ygUPbWFzaHVwIHBsYXlsaXN0oAcB",
 "Aankhon mein doob jaane ko":"https://www.youtube.com/watch?v=PwEvz2FLZ4I&list=RDPwEvz2FLZ4I&start_radio=1&pp=ygUaYWFua2hvbiBtZWluIGRvb2IgamFhbmUga2-gBwE%3D",
 "Pal pal dil ke pass":"https://www.youtube.com/watch?v=lgTHGZF3BQw&list=RDlgTHGZF3BQw&start_radio=1&pp=ygUYcGFsIHBhbCBkaWwga2UgcGFhcyBzb25noAcB",
 "Varoon":"https://www.youtube.com/watch?v=SQ4jZ-EAL88&list=RDSQ4jZ-EAL88&start_radio=1&pp=ygUMdmFhcm9vbiBzb25noAcB",
 "Sheesha":"https://www.youtube.com/watch?v=aRNfSqsgrgE&list=RDaRNfSqsgrgE&start_radio=1&pp=ygUMc2hlZXNoYSBzb25noAcB",
 "Ve kamleya":"https://www.youtube.com/watch?v=QXJyMpxd210&list=RDQXJyMpxd210&start_radio=1&pp=ygUPdmUga2FtbGV5YSBzb25noAcB",
 "naino ki ghat":"https://www.youtube.com/watch?v=qZ9mldIqEs0&list=RDqZ9mldIqEs0&start_radio=1&pp=ygUhbmFpbm8ga2kgZ2hhdCBsZWphIG5haW5vIGtpIG5haXlhoAcB",
 "Tum tak":"https://www.youtube.com/watch?v=AGsn2ycFRqI&list=RDAGsn2ycFRqI&start_radio=1&pp=ygUhbmFpbm8ga2kgZ2hhdCBsZWphIG5haW5vIGtpIG5haXlhoAcB",
 "ishq di baajiyaan":"https://www.youtube.com/watch?v=rnyrDk4G68g&list=RDrnyrDk4G68g&start_radio=1&pp=ygURaXNocSBkaSBiYWFqaXlhYW6gBwE%3D",
 "Tum todo na":"https://www.youtube.com/watch?v=502xhwUiGTs&list=RD502xhwUiGTs&start_radio=1&pp=ygUUdHVtIHRvZG8gbmEgZGlsIG1lcmGgBwE%3D",
 "Dil ka jo haal hai":"https://www.youtube.com/watch?v=udgrClXV26Y&list=RDudgrClXV26Y&start_radio=1&pp=ygUSZGlsIGthIGpvIGhhYWwgaGFpoAcB0gcJCf4LAYcqIYzv",
 "Maan Mera":"https://www.youtube.com/watch?v=HP2zqQsrsyg&list=RDHP2zqQsrsyg&start_radio=1&pp=ygUJbWFhbiBtZXJhoAcB",
 "Aakhone se batana":"https://www.youtube.com/watch?v=2vKMY75kvjI&list=RD2vKMY75kvjI&start_radio=1&pp=ygURYWFua2hvbiBzZSBiYXRhbmGgBwE%3D",
 "Neele neele Ambar pr":"https://www.youtube.com/watch?v=eVnG_Rqfgg4&list=RDeVnG_Rqfgg4&start_radio=1&pp=ygUVbmVlbGUgbmVlbGUgYW1iYXIgcGFyoAcB",
 "Tenu sang rakhana":"https://www.youtube.com/watch?v=OkpIoEC44kk&list=RDOkpIoEC44kk&start_radio=1&pp=ygUQdGVudSBzYW5nIHJha2huYaAHAQ%3D%3D",
 "Meri liye tum kaafi ho":"https://www.youtube.com/watch?v=5LBB6OV3Ano&list=RD5LBB6OV3Ano&start_radio=1&pp=ygUWbWVyZSBsaXllIHR1bSBrYWFmaSBob6AHAQ%3D%3D",
 "Tu hai kaha":"https://www.youtube.com/watch?v=AX6OrbgS8lI&list=RDAX6OrbgS8lI&start_radio=1&pp=ygUMdHUgaGFpIGthaGFuoAcB",
 "Haan ke haan":"https://www.youtube.com/watch?v=NDjeeJwI08Q&list=RDNDjeeJwI08Q&start_radio=1&pp=ygUMaGFhbiBrZSBoYWFuoAcB0gcJCf4LAYcqIYzv",
 "Pehle bhi main":"https://www.youtube.com/watch?v=iAIBF2ngbWY&list=RDiAIBF2ngbWY&start_radio=1&pp=ygUWcGhsZSBiIG0gdHVtc2UgbWlsYSBodaAHAQ%3D%3D",
 "Kaali bindi":"https://www.youtube.com/watch?v=R-SmeE-0rdg&list=RDR-SmeE-0rdg&start_radio=1&pp=ygULa2FhbGkgYmluZGmgBwE%3D",
 "Gulabi sadi":"https://www.youtube.com/watch?v=B_6d3RBiEN0&list=RDB_6d3RBiEN0&start_radio=1&pp=ygULZ3VsYWJpIHNhZGmgBwE%3D",
 "Bullet wali":"https://www.youtube.com/watch?v=NpVDVw-OlgY&list=RDNpVDVw-OlgY&start_radio=1&pp=ygULYnVsbGV0IHdhbGmgBwE%3D",
 "Sang rahiyo":"https://www.youtube.com/watch?v=8PTOkwze0Vw&list=RD8PTOkwze0Vw&start_radio=1&pp=ygULc2FuZyByYWhpeW-gBwE%3D",
 "o maahi":"https://www.youtube.com/watch?v=Etkd-07gnxM&list=RDEtkd-07gnxM&start_radio=1&pp=ygUHbyBtYWFoaaAHAQ%3D%3D",
 "Luka chuppi":"https://www.youtube.com/watch?v=WjjKlwt0UNk&list=RDWjjKlwt0UNk&start_radio=1&pp=ygULbHVrYSBjaHVwcGmgBwE%3D",
 "Shivba Raja":"https://www.youtube.com/watch?v=gAzMqmenkMY&list=RDgAzMqmenkMY&start_radio=1&pp=ygULc2hpdmJhIHJhamGgBwHSBwkJ_gsBhyohjO8%3D"

}